--- #Basic provisioning example
- hosts: localhost
  gather_facts: true
  tasks:
   - name: launching ec2
     ec2:
        key_name: b40
        region: eu-west-1
        instance_type: t2.micro
        image: ami-0ea0f26a6d50850c5
        wait: yes
        group: default
        count: 1
        vpc_subnet_id: subnet-04700d1e27e7fa2d0
        assign_public_ip: yes